/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//cart': RouteRecordInfo<'//cart', '/cart', Record<never, never>, Record<never, never>>,
    '//products/[id]': RouteRecordInfo<'//products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//settings': RouteRecordInfo<'//settings', '/settings', Record<never, never>, Record<never, never>>,
    '//settings/': RouteRecordInfo<'//settings/', '/settings', Record<never, never>, Record<never, never>>,
    '//settings/password': RouteRecordInfo<'//settings/password', '/settings/password', Record<never, never>, Record<never, never>>,
    '//thanks': RouteRecordInfo<'//thanks', '/thanks', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/brands/': RouteRecordInfo<'/admin/brands/', '/admin/brands', Record<never, never>, Record<never, never>>,
    '/admin/categories/': RouteRecordInfo<'/admin/categories/', '/admin/categories', Record<never, never>, Record<never, never>>,
    '/admin/products/': RouteRecordInfo<'/admin/products/', '/admin/products', Record<never, never>, Record<never, never>>,
    '/admin/products/[id]': RouteRecordInfo<'/admin/products/[id]', '/admin/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
  }
}
